### ISSUE TITLE
Change position of axis labels when showing text answers vs numerical answers

### ISSUE THREAD

**Issue by odashj** [sosolimited/Design-Census#15]
![screen shot 2017-01-04 at 12 14 27 pm](https://cloud.githubusercontent.com/assets/14224242/21651630/5f344e3c-d277-11e6-8f42-f57cc17bc068.png)

Label should be closer to axis when ticks are numbers, and further when text

**Comment by jcnesci** [comment]
- clean Olivia's code that attempted to do this (if its in there)
- change chart padding on X or Y depending on data type
- make sure Y axis text never overlaps with axis label
