### ISSUE TITLE
Create Loading Screen for Visualization

### ISSUE THREAD

**Issue by odashj** [sosolimited/Design-Census#2]
The viz always takes a few seconds to load, then pops on the screen. 
Include some sort of indication that it is loading + a trasition (fade in?) for when it appears.

**Comment by jcnesci** [comment]
Also maybe loading thing for when selecting dropdowns, like just fade-in/out the data.

**Comment by odashj** [comment]
@jcnesci I can try tackling this one if you haven't started yet

**Comment by jcnesci** [comment]
@odashj If you need something to do, try it out, sure!
