### ISSUE TITLE
Remove "organization-position" answers that have least amount of data

### ISSUE THREAD

**Issue by odashj** [sosolimited/Design-Census#4]
There are too many answers to plot on the axis. We need to shorten the results to a max of ~17 or combine similar categories.

![screen shot 2017-01-03 at 5 16 27 pm](https://cloud.githubusercontent.com/assets/14224242/21625169/654c25be-d1d8-11e6-827d-1727a46b8ef6.png)

**Comment by jcnesci** [comment]
User might expect the answers to be the real ones. Not sure if we can/should "smudge" the data this way. 
@justinmanor could weigh in maybe?

**Comment by jackielittman** [comment]
Have we tried using a tiny type size for axis labels when there are more than X number of categories?

**Comment by jcnesci** [comment]
@jackielittman I don't think so. Easy to test.

**Comment by odashj** [comment]
Here it is at 8pt. Definitely not the best solution

![screen shot 2017-01-04 at 2 02 30 pm](https://cloud.githubusercontent.com/assets/14224242/21655104/916386ac-d286-11e6-9072-f7565fbeae0f.png)

**Comment by jackielittman** [comment]
Not great, but at least more readable

-- 
Sosolimited
214 Cambridge St #4
Boston, MA 02114
617.350.7676
www.sosolimited.com

**Comment by jcnesci** [comment]
@jackielittman Olivia should be going over the answer items' text to shorten them. It won't reduce the number of items yet, but it should help make it more legible, at least.

**Comment by jcnesci** [comment]
UPDATE:
- @odashj to shorten answer label text, then, if that isn't good enough, Justin says to try removing empty data rows/columns, then combine into less categories if necessary

**Comment by odashj** [comment]
We're going to try to avoid combining categories and instead clear empty rows and make the text smaller.

**Comment by jcnesci** [comment]
Split into #22 and #23
