### ISSUE TITLE
Decrease text box width for ticker labels

### ISSUE THREAD

**Issue by odashj** [sosolimited/Design-Census#5]
If a label exceeds a certain number of characters, make it go onto two lines, or shorten it with '...'

**Comment by jcnesci** [comment]
Ex:
- org-industry
- org-position

Ideas:
- Junior > Jr, Senior > Sr
- add new property to CSV file with shorter titles
- if longer than 15 chars, cut and add '...'

**Comment by jcnesci** [comment]
get opinion from @jackielittman @justinmanor

**Comment by jcnesci** [comment]
UPDATE:
- @odashj to shorten answer text, then we'll see if not good enough
